<a href="https://colab.research.google.com/github/shivamvishwakarma9035/Breast-cancer-predictor/blob/main/Tensors_Operations1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.5.1+cu124


In [ ]:
if torch.cuda.is_available():
    print("GPU is available.")
    print(f"Using GPU:{torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available.")

GPU is available.
Using GPU:Tesla T4


Creating a tensor


In [ ]:
# using empty
a=torch.empty(2,3)

In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
# using zeroes
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch .ones(2,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# using rand which generate float number in between o and 1
torch.rand(2,3)


tensor([[0.7655, 0.6336, 0.7465],
        [0.5611, 0.8235, 0.2573]])

In [ ]:
# use of seed
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [ ]:
# using tensors
torch.tensor([[1,2,3],[4,4,5]])

tensor([[1, 2, 3],
        [4, 4, 5]])

In [ ]:
# other ways
# range
print("using range->",torch.arange(10,20,2))

# using linspace
print("using linspace->",torch.linspace(0,10,10))

# using eye
print("using eye->",torch.eye(3))

# using diag
print("using diag->",torch.diag(torch.tensor([1,2,3])))

# using full
print("using full->",torch.full((3,3),2))

using range-> tensor([10, 12, 14, 16, 18])
using linspace-> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye-> tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
using diag-> tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])
using full-> tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])


Tensors shape

In [ ]:
x=torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like (x)
#shape will be same as x but value can be different

tensor([[170708808,      1107, 170708648],
        [       53, 170708840,      1099]])

In [38]:
print(torch.zeros_like(x))
torch.ones_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])


tensor([[1, 1, 1],
        [1, 1, 1]])

In [47]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

**Tensor Date Type**

In [40]:
x.dtype

torch.int64

In [42]:
# assign data type
torch.tensor([1.0,2.99999,3.556],dtype=torch.int64)

tensor([1, 2, 3])

In [45]:
torch.tensor([1,2.1,3],dtype=torch.float64)

tensor([1.0000, 2.1000, 3.0000], dtype=torch.float64)

In [46]:
# using to
x.to(torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

# 1.Scaler Operation

In [55]:
# Adiition
x=torch.tensor([1,2,3])
y=torch.tensor([4,5,6])
print(x+y)

# Substraction
print(x-y)

# Multiplication
print(x*y)

# Division
print(x/y)

# mod
print(x%y)

# power
print(x**y)


#abslute  using troch.abs(x)
# and many more like negative ,round,seal,floor,clamp

tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([ 4, 10, 18])
tensor([0.2500, 0.4000, 0.5000])
tensor([1, 2, 3])
tensor([  1,  32, 729])


# 3.Reduction operation

In [71]:
y=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float64)
y

tensor([[8., 2., 1.],
        [0., 0., 6.]], dtype=torch.float64)

In [72]:
print(torch.sum(y))
# sum along columns
print(torch.sum(y,dim=0))
# sum along rows
torch.sum(y,dim=1)

tensor(17., dtype=torch.float64)
tensor([8., 2., 7.], dtype=torch.float64)


tensor([11.,  6.], dtype=torch.float64)

In [75]:
#mean
print(torch.mean(y))
# along columns
torch.mean(y,dim=0)
# along rows
torch.mean(y,dim=1)

tensor(2.8333, dtype=torch.float64)


tensor([3.6667, 2.0000], dtype=torch.float64)

In [77]:
# median
torch.median(y)

tensor(1., dtype=torch.float64)

In [80]:
# product
torch.prod(y)

tensor(0., dtype=torch.float64)

In [81]:
# tsnaddard deviation
torch.std(y)

tensor(3.3714, dtype=torch.float64)

In [82]:
# variance
torch.var(y)

tensor(11.3667, dtype=torch.float64)

In [87]:
# argmax and arg min  -> they will tell th position number of max and min number of tensor
torch.argmax(y)
torch.argmin(y)


tensor(3)

# Matrix operation

In [88]:
# matrix multiplication

In [89]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)
print(f)
print(g)


tensor([[5, 0, 6],
        [9, 2, 4]])
tensor([[2, 0],
        [2, 3],
        [3, 1]])


In [90]:
torch.matmul(f,g)

tensor([[28,  6],
        [34, 10]])

In [92]:
# can do dot product in similar fashion

In [95]:
# transpose
torch.transpose(f,0,1)

tensor([[5, 9],
        [0, 2],
        [6, 4]])

In [98]:
# determinant
x=torch.tensor([[2,2],[3,4]],dtype=torch.float32)
torch.det(x)

tensor(2.)

In [99]:
# inverse can also be calculate

# Comparision


In [122]:
p=torch.randint(size=(2,3),low=1,high=10,dtype=torch.float64)
q=torch.randint(size=(2,3),low=0,high=10)
print(p)
q

tensor([[2., 2., 9.],
        [5., 3., 4.]], dtype=torch.float64)


tensor([[5, 2, 4],
        [8, 4, 3]])

In [123]:
p>q

tensor([[False, False,  True],
        [False, False,  True]])

In [124]:
# log
torch.log(p)


tensor([[0.6931, 0.6931, 2.1972],
        [1.6094, 1.0986, 1.3863]], dtype=torch.float64)

In [125]:
# exp
torch.exp(p)


tensor([[7.3891e+00, 7.3891e+00, 8.1031e+03],
        [1.4841e+02, 2.0086e+01, 5.4598e+01]], dtype=torch.float64)

In [126]:
#sqrt
torch.sqrt(p)

tensor([[1.4142, 1.4142, 3.0000],
        [2.2361, 1.7321, 2.0000]], dtype=torch.float64)

In [127]:
# sigmoid
torch.sigmoid(p)

tensor([[0.8808, 0.8808, 0.9999],
        [0.9933, 0.9526, 0.9820]], dtype=torch.float64)

In [128]:
# softmax
torch.softmax(p,dim=0)

tensor([[0.0474, 0.2689, 0.9933],
        [0.9526, 0.7311, 0.0067]], dtype=torch.float64)

In [129]:
# relu
torch.relu(p)

tensor([[2., 2., 9.],
        [5., 3., 4.]], dtype=torch.float64)

# Inplace Operations

In [136]:
m=torch.randint(size=(2,3),low=0,high=10)
n=torch.randint(size=(2,3),low=0,high=10)
print(m)
n

tensor([[7, 3, 7],
        [7, 2, 5]])


tensor([[4, 7, 2],
        [3, 7, 9]])

In [137]:
m+n

tensor([[11, 10,  9],
        [10,  9, 14]])

In [138]:
m.add_(n)

tensor([[11, 10,  9],
        [10,  9, 14]])

In [139]:
m+n

tensor([[15, 17, 11],
        [13, 16, 23]])

In [140]:
m

tensor([[11, 10,  9],
        [10,  9, 14]])

In [141]:
torch.relu(m)

tensor([[11, 10,  9],
        [10,  9, 14]])

In [142]:
m.relu_()

tensor([[11, 10,  9],
        [10,  9, 14]])

# Copying a Tensor

In [143]:
a=torch.rand(2,3)
a

tensor([[0.4563, 0.2539, 0.2956],
        [0.3413, 0.0248, 0.9103]])

In [145]:
b=a
b

tensor([[0.4563, 0.2539, 0.2956],
        [0.3413, 0.0248, 0.9103]])

In [146]:
a[0][0]=0
a

tensor([[0.0000, 0.2539, 0.2956],
        [0.3413, 0.0248, 0.9103]])

In [147]:
b

tensor([[0.0000, 0.2539, 0.2956],
        [0.3413, 0.0248, 0.9103]])

In [148]:
id(b)

136222358728208

In [149]:
id(a)

136222358728208

In [151]:
b=a.clone()
a

tensor([[0.0000, 0.2539, 0.2956],
        [0.3413, 0.0248, 0.9103]])